[package]
name = "cmp-gcs-siphash24-blake2b"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-hash = "0.103.0"
bitcoin_hashes = "0.7.3"
rand = "0.8.5"